# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)

name: Docs

on:
  workflow_dispatch:
    inputs:
      publish:
        default: false
        type: boolean
  workflow_call:
    inputs:
      publish:
        default: false
        type: boolean

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # This is required for uploading the assets to the release

    steps:
      - run: sudo apt install --yes graphviz pandoc
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements/ci.txt
      - run: tox -e docs
      - run: zip -r docs_html.zip docs_html
        if: ${{ inputs.publish }}

      - uses: actions/upload-artifact@v3
        with:
          name: Documentation
          path: docs_html/

      - uses: JamesIves/github-pages-deploy-action@v4.4.3
        if: ${{ inputs.publish }}
        with:
          branch: gh-pages
          folder: docs_html
          target-folder: ${{ env.target }}
          single-commit: true

      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        if: ${{ inputs.publish }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: docs_html.zip
          asset_name: docs_html.zip
          tag: ${{ github.ref }}
          overwrite: true
